#!/bin/bash

_arch=$1

if [ -z "${_arch}" ]; then
    _arch=x86_64
fi

if [ -z "${RETROROOT_HOME}" ]; then
    export RETROROOT_HOME=/opt/retroroot
fi

# sysroot path
if [ -z "${RETROROOT_SYSROOT}" ]; then
    export RETROROOT_SYSROOT=${RETROROOT_HOME}/target/${_arch}
fi

# toolchain setup
if [ -z "${RETROROOT_HOST}" ]; then
    export RETROROOT_HOST=${RETROROOT_HOME}/host/${_arch}
fi

export RETROROOT_CROSS_PREFIX=${_arch}-linux-gnu-

export RETROROOT_CC=${RETROROOT_CROSS_PREFIX}gcc
export RETROROOT_CXX=${RETROROOT_CROSS_PREFIX}g++
export RETROROOT_LD=${RETROROOT_CROSS_PREFIX}ld
export RETROROOT_AR=${RETROROOT_CROSS_PREFIX}ar
export RETROROOT_AS=${RETROROOT_CROSS_PREFIX}as
export RETROROOT_NM=${RETROROOT_CROSS_PREFIX}nm
export RETROROOT_RANLIB=${RETROROOT_CROSS_PREFIX}ranlib
export RETROROOT_STRIP=${RETROROOT_CROSS_PREFIX}strip
export RETROROOT_PKGCONFIG=${RETROROOT_CROSS_PREFIX}pkg-config

export AS="${RETROROOT_AS} --sysroot=${RETROROOT_SYSROOT}"
export CC="${RETROROOT_CC} --sysroot=${RETROROOT_SYSROOT}"
export CXX="${RETROROOT_CXX} --sysroot=${RETROROOT_SYSROOT}"
export LD="${RETROROOT_LD} --sysroot=${RETROROOT_SYSROOT}"
export AR="${RETROROOT_AR}"
export NM="${RETROROOT_NM}"
export RANLIB="${RETROROOT_RANLIB}"
export STRIP="${RETROROOT_STRIP}"
export CFLAGS="-I${RETROROOT_SYSROOT}/usr/include -O2 -pipe -fno-plt -D__RETROROOT__ ${CFLAGS}"
export CPPFLAGS="${CFLAGS} ${CPPFLAGS} -fexceptions"
export CXXFLAGS="${CFLAGS} ${CXXFLAGS} -fexceptions"
export LDFLAGS="-L${RETROROOT_SYSROOT}/usr/lib ${LDFLAGS}"
# -Wl,-O1,--sort-common,--as-needed
# arch specific
if [ ${_arch} == "x86_64" ]; then
  export CFLAGS="${CFLAGS}"
  export CPPFLAGS="${CPPFLAGS}"
  export CXXFLAGS="${CXXFLAGS}"
elif [ ${_arch} == "armv7h" ]; then
  export CFLAGS="${CFLAGS} -march=armv7-a -mfloat-abi=hard -mfpu=neon"
  export CPPFLAGS="${CPPFLAGS} -march=armv7-a -mfloat-abi=hard -mfpu=neon"
  export CXXFLAGS="${CXXFLAGS} -march=armv7-a -mfloat-abi=hard -mfpu=neon"
elif [ ${_arch} == "aarch64" ]; then
  export CFLAGS="${CFLAGS} -march=armv8-a -mcpu=cortex-a35"
  export CPPFLAGS="${CPPFLAGS} -march=armv8-a -mcpu=cortex-a35"
  export CXXFLAGS="${CXXFLAGS} -march=armv8-a -mcpu=cortex-a35"
fi

# pkg config setup
export PKG_CONFIG_DIR=
export PKG_CONFIG_SYSROOT_DIR=${RETROROOT_SYSROOT}
export PKG_CONFIG_LIBDIR=${RETROROOT_SYSROOT}/usr/lib/pkgconfig:${RETROROOT_SYSROOT}/usr/share/pkgconfig
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH_CUSTOM}:${PKG_CONFIG_LIBDIR}

# prefix setup
export RETROROOT_PREFIX=/usr
export RETROROOT_PREFIX_BIN=${RETROROOT_PREFIX}/bin
export RETROROOT_PREFIX_INCLUDE=${RETROROOT_PREFIX}/include
export RETROROOT_PREFIX_LIB=${RETROROOT_PREFIX}/lib
export RETROROOT_PREFIX_ETC=${RETROROOT_PREFIX}/etc
export RETROROOT_PREFIX_SHARE=${RETROROOT_PREFIX}/share

export PATH="${RETROROOT_HOME}:${RETROROOT_SYSROOT}/usr/bin:${RETROROOT_HOST}/bin:$PATH"

