#!/bin/sh

set -xe

source /configs/common/vars

echo "rr-run-parts: $(basename $0)"

# update database and packages
pacman --noconfirm -Syyu

# install common packages
source /configs/common/packages
pacman --noconfirm --needed -S ${RR_PACKAGES}

# install platform specific packages
source /configs/${RR_PLATFORM}/packages
pacman --noconfirm --needed -S ${RR_PACKAGES}

# desktop bootloader (mbr for now)
if [ "${RR_PLATFORM}" == "desktop" ]; then
  syslinux-install_update -iam
fi

# cleanup
rm -rf /var/cache/pacman/pkg

