#!/bin/sh

set -xe

source /configs/common/vars

echo "rr-run-parts: $(basename $0)"

# update database and packages
pacman --noconfirm -Syyu

# install common packages
source /configs/common/packages
pacman --noconfirm --needed -S ${RR_PACKAGES}

# install platform specific packages
source /configs/${RR_PLATFORM}/packages
pacman --noconfirm --needed -S ${RR_PACKAGES}

# disable arch repo (we don't want system updates) and enable retroroot repo
rm /etc/pacman.conf.pacnew
mv /etc/pacman.d/mirrorlist.pacnew /etc/pacman.d/mirrorlist
cp /overlays/${RR_PLATFORM}/etc/pacman.conf /etc/pacman.conf

# install retroroot packages
pacman --noconfirm -Syy
# TODO

# cleanup
rm -rf /var/cache/pacman/pkg

