#!/bin/sh

set -xe

source /configs/common/vars

echo "rr-run-parts: $(basename $0)"

# update database and packages
pacman --noconfirm -Syyu

# install common packages
source /configs/common/packages
pacman --noconfirm --needed -S ${RR_PACKAGES}

# install platform specific packages
source /configs/${RR_PLATFORM}/packages
pacman --noconfirm --needed -S ${RR_PACKAGES}

# cleanup
rm -rf /var/cache/pacman/pkg

