#!/bin/sh

set -xe

source /configs/common/vars

echo "rr-run-parts: $(basename $0)"

# copy common overlay
cp -r /overlays/common/. .

# copy platform overlay
cp -r /overlays/${RR_PLATFORM}/. .

# cleanup package cache and db (we don't want sys updates)
rm -rf /var/cache/pacman/pkg
rm -rf /var/lib/pacman/*
# update retroroot packages
pacman --noconfirm -Syy

# root passwd
echo "root:${RR_ROOT_PASSWORD}" | chpasswd

# create user and groups
useradd -m ${RR_USERNAME}
for GRP in autologin dialout cdrom spi i2c gpio netdev; do
	groupadd -r --system $GRP
done
for GRP in adm dialout cdrom audio users video games input tty gpio spi i2c netdev; do
  usermod -aG $GRP ${RR_USERNAME}
done
echo "${RR_USERNAME}:${RR_USERNAME}" | chpasswd
echo "
root ALL=(ALL) ALL
${RR_USERNAME} ALL=(ALL) ALL
#includedir /etc/sudoers.d
" > /etc/sudoers

# update locales
locale-gen

# enable services
source /configs/common/services
systemctl enable ${RR_SERVICES}

# systemd-networkd resolv.conf handling
#rm /etc/resolv.conf
#ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

# install desktop bootloader (mbr for now)
if [ "${RR_PLATFORM}" == "desktop" ]; then
  syslinux-install_update -iam
  # update initramfs including overlay
  mkinitcpio -p linux
fi

# final cleanup
rm -rf /bootstrap
rm -rf /configs
rm -rf /overlays

