#!/bin/sh

set -xe

source /configs/platforms/common/vars

echo "rr-run-parts: $(basename $0)"

# copy common overlay
cp -r /overlays/common/. .

# copy platform overlay
if [ -d "/overlays/${RR_PLATFORM}" ]; then
  cp -r /overlays/${RR_PLATFORM}/. .
fi

# copy pacman config
cp -f /configs/pacman-${RR_ARCH}.conf /etc/pacman.conf

# cleanup package cache
rm -rf /var/cache/pacman/pkg

# update retroroot database and install retroroot stuff
# todo: use custom "mkinitcpio" package or PKGBUILD override?
pacman --noconfirm -Syy
pacman -S --noconfirm --overwrite "/etc/mkinitcpio.conf" rr-base rr-recovery rr-splash

# root passwd
echo "root:${RR_ROOT_PASSWORD}" | chpasswd

# create local user and groups
useradd -m ${RR_USERNAME}
for GRP in autologin dialout cdrom spi i2c gpio netdev; do
	groupadd -r --system $GRP
done
for GRP in adm dialout cdrom audio users video games input tty gpio spi i2c netdev; do
  usermod -aG $GRP ${RR_USERNAME}
done
echo "${RR_USERNAME}:${RR_USERNAME}" | chpasswd
echo "
root ALL=(ALL) ALL
${RR_USERNAME} ALL=(ALL) ALL
#includedir /etc/sudoers.d
" > /etc/sudoers

# update locales
locale-gen

# enable services
source /configs/platforms/common/services
if [ -f "/configs/platforms/${RR_PLATFORM}/services" ]; then
  source /configs/platforms/${RR_PLATFORM}/services
fi
systemctl enable ${RR_SERVICES}

