#!/bin/sh

set -xe

source /configs/vars

# if toolchain build was requested just skip...
if [ "$RR_BUILD_TOOLCHAIN" == "1" ]; then
  exit 0;
fi

if [ "${RR_PLATFORM}" != "rg353" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename $0)"

# nothing to do here for now...

