#!/bin/sh

set -xe

source /configs/vars

# if toolchain build was requested just skip...
if [ "$RR_BUILD_TOOLCHAIN" == "1" ]; then
  exit 0;
fi

if [ "${RR_PLATFORM}" != "desktop" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename $0)"

# install desktop bootloader (todo: uefi)
syslinux-install_update -iam

# cleanup boot partition
rm -f /boot/initramfs-linux-fallback.img

