#!/bin/sh

set -xe

source /configs/platforms/common/vars

if [ "${RR_PLATFORM}" != "desktop" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename $0)"

# install desktop bootloader (todo: uefi)
syslinux-install_update -iam

# update initramfs including "retroroot" mkinitcpio hook
mkinitcpio -p linux

# minor cleanup
rm -f /boot/initramfs-linux-fallback.img

