#!/bin/sh

set -xe

source /configs/vars

if [ "${RR_PLATFORM}" != "surfacert" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename $0)"

# fix dbus-daemon-units for old systemd
#pacman --noconfirm -S --overwrite "*" dbus-daemon-units

# TODO: fixme
# disable services
#source /configs/services
#systemctl disable ${RR_SERVICES}

