#!/bin/sh

set -xe

source /configs/common/vars

if [ "${RR_PLATFORM}" != "rpi" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename $0)"

# update initramfs including "retroroot" mkinitcpio hook
mkinitcpio -p linux-rpi

