#!/bin/sh

set -xe

source /configs/platforms/common/vars

if [ "${RR_PLATFORM}" != "rp2" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename $0)"

# update initramfs including "retroroot" mkinitcpio hook
mkinitcpio -p linux-rp2

