#!/bin/sh

set -xe

source /retroroot/configs/vars

if [ "${RR_PLATFORM}" != "surfacert" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename "$0")"

# fix for systemd 230 (which use dbus-daemon-units)
pacman --noconfirm -Rdd dbus-broker-units

