#!/bin/bash

set -xe

source /retroroot/configs/vars "$@"

if [ "${RR_PLATFORM}" != "desktop" ]; then
  exit 0;
fi

echo "rr-run-parts: $(basename "$0")"

# install desktop bootloader (todo: uefi)
syslinux-install_update -iam

# cleanup boot partition
rm -f /boot/initramfs-linux-fallback.img

