#!/bin/sh

set -xe

source /configs/vars

echo "rr-run-parts: $(basename $0)"

# enable back pacman CheckSpace option
sed -i 's/#CheckSpace/CheckSpace/g' /etc/pacman.conf
# remove custom package cache directive
sed -i '/CacheDir/d' /etc/pacman.conf
# cleanup pkg cache
rm -rf /output/pacman_cache/${RR_ARCH}/
rm -rf /var/cache/pacman/pkg

# delete build directories
rm -rf /bootstrap
rm -rf /configs

