#!/usr/bin/env bash
SCRIPTDIR="${BASH_SOURCE%/*}"

if [ -z "$1" ]; then
	echo "No platform specified." 1>&2
	exit 1
fi

if [ -z "$2" ]; then
	echo "No cross file output filename specified." 1>&2
	exit 1
fi

ARCH="$1"
CROSSFILE="$2"
shift 2

#PORTLIBS_PREFIX=$(${SCRIPTDIR}/portlibs_prefix.sh ${PLATFORM})
source /opt/retroroot/rr-env $ARCH

${SCRIPTDIR}/rr-meson-toolchain ${ARCH} > ${CROSSFILE} || exit 1
meson --buildtype=plain --cross-file="${CROSSFILE}" \
  --prefix        /usr \
  --libexecdir    lib \
  --sbindir       bin \
  --buildtype     plain \
  --auto-features enabled \
  --wrap-mode     nodownload \
  -D              b_lto=false \
  -D              b_pie=true \
  "$@"
