#!/bin/bash

# downstream kernel (3.4.x) with tegra xorg hw acceleration doesn't work with latest systemd, use older version
# downstream kernel (3.4.x) needs xorg-server ABI 14
export RR_PACKAGES=" \
  linux-downstream-surfacert \
  linux-firmware \
  wpa_supplicant dhclient
"
# systemd=230-7 systemd-sysvcompat=230-7 libsystemd=230-7 systemd-libs-surfacert \
# xorg-server-surfacert xf86-video-tegra-surfacert xf86-input-evdev-surfacert \

