#!/bin/bash

# "base" package
# https://gitlab.archlinux.org/archlinux/packaging/packages/base/-/blob/main/PKGBUILD?ref_type=heads
export RR_PACKAGES=${RR_PACKAGES}" \
  base
"

# extra utilites
export RR_PACKAGES=${RR_PACKAGES}" \
  run-parts \
  mkinitcpio \
  fakeroot \
  net-tools \
  dosfstools \
  bash-completion \
  sudo \
  nano \
  wget \
  less \
  openssh \
  strace \
  vsftpd \
  inetutils \
  wireless-regdb \
  alsa-utils
"

# emulation stuff
export RR_PACKAGES=${RR_PACKAGES}" \
  mesa mesa-vdpau libva-mesa-driver libglvnd \
  retroarch \
  retroarch-assets-glui \
  retroarch-assets-ozone \
  retroarch-assets-xmb \
  libretro-overlays \
  libretro-shaders \
  libretro-snes9x \
  libretro-flycast
"

