#!/bin/bash

# "base" package
# https://gitlab.archlinux.org/archlinux/packaging/packages/base/-/blob/main/PKGBUILD?ref_type=heads
export RR_PACKAGES=${RR_PACKAGES}" \
  filesystem gcc-libs glibc bash \
  coreutils file findutils gawk grep procps-ng sed tar \
  gettext pciutils psmisc shadow util-linux bzip2 gzip xz \
  licenses pacman archlinux-keyring systemd systemd-sysvcompat \
  iputils iproute2
"

# extra utilites
export RR_PACKAGES=${RR_PACKAGES}" \
  run-parts \
  net-tools \
  dosfstools \
  bash-completion \
  sudo \
  nano \
  wget \
  less \
  openssh \
  strace \
  vsftpd \
  inetutils \
  wireless-regdb
"
# squashfs-tools iwd

# "portlibs"
export RR_PACKAGES_DISABLED_SURFACERT_TESTING=${RR_PACKAGES}" \
  asio \
  boost \
  box2d \
  bullet \
  bzip2 \
  curl \
  enet \
  expat \
  ffmpeg \
  flac \
  fmt \
  fontconfig \
  freetype2 \
  fribidi \
  fftw \
  fuse2 \
  gd \
  giflib \
  glew \
  glm \
  harfbuzz \
  hidapi \
  icu \
  jack \
  jansson \
  json-c \
  jsoncpp \
  lame \
  libass \
  libarchive \
  libconfig \
  libevdev \
  libexif \
  libimagequant \
  libinput \
  libjpeg-turbo \
  libmad \
  libmikmod \
  libmodplug \
  libmpeg2 \
  libogg \
  libpng \
  libpulse \
  libsamplerate \
  libsigc++ \
  libsigc++-3.0 \
  libsndfile \
  libsodium \
  libssh2 \
  libtheora \
  libunrar \
  libusb \
  libvorbis \
  libvpx \
  libwebp \
  libwslay \
  libxext \
  libxml2 \
  love \
  lua \
  lz4 \
  lzo \
  mbedtls \
  miniupnpc \
  minizip \
  mpg123 \
  mpv \
  ode \
  oniguruma \
  openal \
  openssl \
  opus \
  opusfile \
  pcre2 \
  physfs \
  sdl \
  sdl_gfx \
  sdl_image \
  sdl_mixer \
  sdl_net \
  sdl_ttf \
  sdl2 \
  sdl2_gfx \
  sdl2_image \
  sdl2_mixer \
  sdl2_net \
  sdl2_ttf \
  smpeg \
  speexdsp \
  timidity++ \
  tinyxml2 \
  xz \
  yaml-cpp \
  zlib \
  zstd \
  zziplib
"
