#!/bin/bash

export RR_PACKAGES=${RR_PACKAGES}"\
  mesa \
  libglvnd \
  linux-surfacert-downstream \
  linux-firmware \
  wpa_supplicant
"
# mesa-vdpau linux-firmware-marvell
# wpa_supplicant dhclient

