#!/bin/bash

# args passed from "build-image.sh" run-parts
export RR_PLATFORM="$1"
export RR_ARCH="$2"
export RR_ROOT_PASSWORD=retroroot
export RR_USERNAME=rr

if [ -f "/retroroot/configs/vars-${RR_PLATFORM}" ]; then
  source "/retroroot/configs/vars-${RR_PLATFORM}"
fi

