#!/bin/bash

target=$1
shift

source "${RETROROOT_HOME}"/rr-env $target

./configure \
  --host=$target-linux-gnu \
  --target=$target-linux-gnu \
  --build=${CHOST} \
  --prefix=${RETROROOT_PREFIX} \
  --libdir=${RETROROOT_PREFIX_LIB} \
  --includedir=${RETROROOT_PREFIX_INCLUDE} \
  --disable-shared \
  --enable-static \
  "$@"

